# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NoticeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Notice(object):
    def setupUi(self, Notice):
        Notice.setObjectName("Notice")
        Notice.resize(400, 450)
        Notice.setStyleSheet("QLabel{color: rgb(255, 255, 255);}")
        self.label_haksa = QtWidgets.QLabel(Notice)
        self.label_haksa.setGeometry(QtCore.QRect(10, 5, 90, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_haksa.setFont(font)
        self.label_haksa.setStyleSheet("")
        self.label_haksa.setObjectName("label_haksa")
        self.label_haksa_num1 = QtWidgets.QLabel(Notice)
        self.label_haksa_num1.setGeometry(QtCore.QRect(10, 30, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_num1.setFont(font)
        self.label_haksa_num1.setObjectName("label_haksa_num1")
        self.label_haksa_date1 = QtWidgets.QLabel(Notice)
        self.label_haksa_date1.setGeometry(QtCore.QRect(120, 30, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_date1.setFont(font)
        self.label_haksa_date1.setObjectName("label_haksa_date1")
        self.label_haksa_sub1 = QtWidgets.QLabel(Notice)
        self.label_haksa_sub1.setGeometry(QtCore.QRect(18, 50, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_sub1.setFont(font)
        self.label_haksa_sub1.setObjectName("label_haksa_sub1")
        self.label_haksa_sub2 = QtWidgets.QLabel(Notice)
        self.label_haksa_sub2.setGeometry(QtCore.QRect(18, 90, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_sub2.setFont(font)
        self.label_haksa_sub2.setObjectName("label_haksa_sub2")
        self.label_haksa_date2 = QtWidgets.QLabel(Notice)
        self.label_haksa_date2.setGeometry(QtCore.QRect(120, 70, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_date2.setFont(font)
        self.label_haksa_date2.setObjectName("label_haksa_date2")
        self.label_haksa_num2 = QtWidgets.QLabel(Notice)
        self.label_haksa_num2.setGeometry(QtCore.QRect(10, 70, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_num2.setFont(font)
        self.label_haksa_num2.setObjectName("label_haksa_num2")
        self.label_haksa_num3 = QtWidgets.QLabel(Notice)
        self.label_haksa_num3.setGeometry(QtCore.QRect(10, 110, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_num3.setFont(font)
        self.label_haksa_num3.setObjectName("label_haksa_num3")
        self.label_haksa_sub3 = QtWidgets.QLabel(Notice)
        self.label_haksa_sub3.setGeometry(QtCore.QRect(18, 130, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_sub3.setFont(font)
        self.label_haksa_sub3.setObjectName("label_haksa_sub3")
        self.label_haksa_date3 = QtWidgets.QLabel(Notice)
        self.label_haksa_date3.setGeometry(QtCore.QRect(120, 110, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_date3.setFont(font)
        self.label_haksa_date3.setObjectName("label_haksa_date3")
        self.label_job_sub1 = QtWidgets.QLabel(Notice)
        self.label_job_sub1.setGeometry(QtCore.QRect(18, 200, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_sub1.setFont(font)
        self.label_job_sub1.setObjectName("label_job_sub1")
        self.label_job_sub3 = QtWidgets.QLabel(Notice)
        self.label_job_sub3.setGeometry(QtCore.QRect(18, 280, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_sub3.setFont(font)
        self.label_job_sub3.setObjectName("label_job_sub3")
        self.label_job_num2 = QtWidgets.QLabel(Notice)
        self.label_job_num2.setGeometry(QtCore.QRect(10, 220, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_num2.setFont(font)
        self.label_job_num2.setObjectName("label_job_num2")
        self.label_job_date3 = QtWidgets.QLabel(Notice)
        self.label_job_date3.setGeometry(QtCore.QRect(120, 260, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_date3.setFont(font)
        self.label_job_date3.setObjectName("label_job_date3")
        self.label_job_sub2 = QtWidgets.QLabel(Notice)
        self.label_job_sub2.setGeometry(QtCore.QRect(18, 240, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_sub2.setFont(font)
        self.label_job_sub2.setObjectName("label_job_sub2")
        self.label_job_num3 = QtWidgets.QLabel(Notice)
        self.label_job_num3.setGeometry(QtCore.QRect(10, 260, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_num3.setFont(font)
        self.label_job_num3.setObjectName("label_job_num3")
        self.label_job_date1 = QtWidgets.QLabel(Notice)
        self.label_job_date1.setGeometry(QtCore.QRect(120, 180, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_date1.setFont(font)
        self.label_job_date1.setObjectName("label_job_date1")
        self.label_job = QtWidgets.QLabel(Notice)
        self.label_job.setGeometry(QtCore.QRect(10, 155, 90, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_job.setFont(font)
        self.label_job.setStyleSheet("")
        self.label_job.setObjectName("label_job")
        self.label_job_num1 = QtWidgets.QLabel(Notice)
        self.label_job_num1.setGeometry(QtCore.QRect(10, 180, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_num1.setFont(font)
        self.label_job_num1.setObjectName("label_job_num1")
        self.label_job_date2 = QtWidgets.QLabel(Notice)
        self.label_job_date2.setGeometry(QtCore.QRect(120, 220, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_date2.setFont(font)
        self.label_job_date2.setObjectName("label_job_date2")
        self.label_general_sub1 = QtWidgets.QLabel(Notice)
        self.label_general_sub1.setGeometry(QtCore.QRect(18, 350, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_sub1.setFont(font)
        self.label_general_sub1.setObjectName("label_general_sub1")
        self.label_general_sub3 = QtWidgets.QLabel(Notice)
        self.label_general_sub3.setGeometry(QtCore.QRect(18, 430, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_sub3.setFont(font)
        self.label_general_sub3.setObjectName("label_general_sub3")
        self.label_general_num2 = QtWidgets.QLabel(Notice)
        self.label_general_num2.setGeometry(QtCore.QRect(10, 370, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_num2.setFont(font)
        self.label_general_num2.setObjectName("label_general_num2")
        self.label_general_date3 = QtWidgets.QLabel(Notice)
        self.label_general_date3.setGeometry(QtCore.QRect(120, 410, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_date3.setFont(font)
        self.label_general_date3.setObjectName("label_general_date3")
        self.label_general_sub2 = QtWidgets.QLabel(Notice)
        self.label_general_sub2.setGeometry(QtCore.QRect(18, 390, 371, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_sub2.setFont(font)
        self.label_general_sub2.setObjectName("label_general_sub2")
        self.label_general_num3 = QtWidgets.QLabel(Notice)
        self.label_general_num3.setGeometry(QtCore.QRect(10, 410, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_num3.setFont(font)
        self.label_general_num3.setObjectName("label_general_num3")
        self.label_general_date1 = QtWidgets.QLabel(Notice)
        self.label_general_date1.setGeometry(QtCore.QRect(120, 330, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_date1.setFont(font)
        self.label_general_date1.setObjectName("label_general_date1")
        self.label_general = QtWidgets.QLabel(Notice)
        self.label_general.setGeometry(QtCore.QRect(10, 305, 90, 18))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_general.setFont(font)
        self.label_general.setStyleSheet("")
        self.label_general.setObjectName("label_general")
        self.label_general_num1 = QtWidgets.QLabel(Notice)
        self.label_general_num1.setGeometry(QtCore.QRect(10, 330, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_num1.setFont(font)
        self.label_general_num1.setObjectName("label_general_num1")
        self.label_general_date2 = QtWidgets.QLabel(Notice)
        self.label_general_date2.setGeometry(QtCore.QRect(120, 370, 95, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_date2.setFont(font)
        self.label_general_date2.setObjectName("label_general_date2")
        self.label_haksa_writer1 = QtWidgets.QLabel(Notice)
        self.label_haksa_writer1.setGeometry(QtCore.QRect(230, 30, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_writer1.setFont(font)
        self.label_haksa_writer1.setObjectName("label_haksa_writer1")
        self.label_haksa_writer2 = QtWidgets.QLabel(Notice)
        self.label_haksa_writer2.setGeometry(QtCore.QRect(230, 70, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_writer2.setFont(font)
        self.label_haksa_writer2.setObjectName("label_haksa_writer2")
        self.label_haksa_writer3 = QtWidgets.QLabel(Notice)
        self.label_haksa_writer3.setGeometry(QtCore.QRect(230, 110, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_haksa_writer3.setFont(font)
        self.label_haksa_writer3.setObjectName("label_haksa_writer3")
        self.label_job_writer1 = QtWidgets.QLabel(Notice)
        self.label_job_writer1.setGeometry(QtCore.QRect(230, 180, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_writer1.setFont(font)
        self.label_job_writer1.setObjectName("label_job_writer1")
        self.label_job_writer3 = QtWidgets.QLabel(Notice)
        self.label_job_writer3.setGeometry(QtCore.QRect(230, 260, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_writer3.setFont(font)
        self.label_job_writer3.setObjectName("label_job_writer3")
        self.label_job_writer2 = QtWidgets.QLabel(Notice)
        self.label_job_writer2.setGeometry(QtCore.QRect(230, 220, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_job_writer2.setFont(font)
        self.label_job_writer2.setObjectName("label_job_writer2")
        self.label_general_writer1 = QtWidgets.QLabel(Notice)
        self.label_general_writer1.setGeometry(QtCore.QRect(230, 330, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_writer1.setFont(font)
        self.label_general_writer1.setObjectName("label_general_writer1")
        self.label_general_writer3 = QtWidgets.QLabel(Notice)
        self.label_general_writer3.setGeometry(QtCore.QRect(230, 410, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_writer3.setFont(font)
        self.label_general_writer3.setObjectName("label_general_writer3")
        self.label_general_writer2 = QtWidgets.QLabel(Notice)
        self.label_general_writer2.setGeometry(QtCore.QRect(230, 370, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_general_writer2.setFont(font)
        self.label_general_writer2.setObjectName("label_general_writer2")

        self.retranslateUi(Notice)
        QtCore.QMetaObject.connectSlotsByName(Notice)

    def retranslateUi(self, Notice):
        _translate = QtCore.QCoreApplication.translate
        Notice.setWindowTitle(_translate("Notice", "NoticeWidget"))
        self.label_haksa.setText(_translate("Notice", "학사공지"))
        self.label_haksa_num1.setText(_translate("Notice", "- 번호 12345"))
        self.label_haksa_date1.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_haksa_sub1.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_haksa_sub2.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_haksa_date2.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_haksa_num2.setText(_translate("Notice", "- 번호 12345"))
        self.label_haksa_num3.setText(_translate("Notice", "- 번호 12345"))
        self.label_haksa_sub3.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_haksa_date3.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_job_sub1.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_job_sub3.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_job_num2.setText(_translate("Notice", "- 번호 12345"))
        self.label_job_date3.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_job_sub2.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_job_num3.setText(_translate("Notice", "- 번호 12345"))
        self.label_job_date1.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_job.setText(_translate("Notice", "장학공지"))
        self.label_job_num1.setText(_translate("Notice", "- 번호 12345"))
        self.label_job_date2.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_general_sub1.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_general_sub3.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_general_num2.setText(_translate("Notice", "- 번호 12345"))
        self.label_general_date3.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_general_sub2.setText(_translate("Notice", "내용가리어카센타조알라딘에서책사고싶다람쥐유아이놈들아"))
        self.label_general_num3.setText(_translate("Notice", "- 번호 12345"))
        self.label_general_date1.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_general.setText(_translate("Notice", "일반공지"))
        self.label_general_num1.setText(_translate("Notice", "- 번호 12345"))
        self.label_general_date2.setText(_translate("Notice", "날짜 2018.05.11"))
        self.label_haksa_writer1.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_haksa_writer2.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_haksa_writer3.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_job_writer1.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_job_writer3.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_job_writer2.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_general_writer1.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_general_writer3.setText(_translate("Notice", "작성자 교수학습지원센터"))
        self.label_general_writer2.setText(_translate("Notice", "작성자 교수학습지원센터"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Notice = QtWidgets.QWidget()
    ui = Ui_Notice()
    ui.setupUi(Notice)
    Notice.show()
    sys.exit(app.exec_())

