from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5.QtGui import *

class ShuttleWidget(QWidget):
	def __init__(self, parent):
		super(ShuttleWidget, self).__init__(parent)
		self.gridLayout_2 = QGridLayout(self)
		self.gridLayout_2.setObjectName("gridLayout_2")
		self.gridLayout = QGridLayout()
		self.gridLayout.setObjectName("gridLayout")
		self.line = QFrame(self)
		self.line.setFrameShape(QFrame.HLine)
		self.line.setFrameShadow(QFrame.Sunken)
		self.line.setObjectName("line")
		self.gridLayout.addWidget(self.line, 1, 0, 1, 6)
		self.line_2 = QFrame(self)
		self.line_2.setFrameShape(QFrame.HLine)
		self.line_2.setFrameShadow(QFrame.Sunken)
		self.line_2.setObjectName("line_2")
		self.gridLayout.addWidget(self.line_2, 3, 0, 1, 6)
		self.label_5 = QLabel(self)
		self.label_5.setStyleSheet("image: url(start.png);")
		self.label_5.setText("")
		self.label_5.setObjectName("label_5")
		self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
		self.destination = QLabel(self)
		self.destination.setStyleSheet("font: 10pt \"HY헤드라인M\";\n"
"color : rgb(255, 32, 43);")
		self.destination.setAlignment(Qt.AlignCenter)
		self.destination.setObjectName("destination")
		self.gridLayout.addWidget(self.destination, 2, 5, 1, 1)
		self.label_3 = QLabel(self)
		self.label_3.setStyleSheet("image: url(finish.png);")
		self.label_3.setText("")
		self.label_3.setObjectName("label_3")
		self.gridLayout.addWidget(self.label_3, 2, 4, 1, 1)
		self.label_7 = QLabel(self)
		self.label_7.setStyleSheet("image: url(kpu.png);")
		self.label_7.setText("")
		self.label_7.setObjectName("label_7")
		self.gridLayout.addWidget(self.label_7, 0, 0, 1, 2)
		self.label_4 = QLabel(self)
		self.label_4.setStyleSheet("font: 14pt \"HY헤드라인M\";")
		self.label_4.setAlignment(Qt.AlignCenter)
		self.label_4.setObjectName("label_4")
		self.gridLayout.addWidget(self.label_4, 0, 2, 1, 4)
		self.departure = QLabel(self)
		self.departure.setStyleSheet("font: 10pt \"HY헤드라인M\";\n"
"color : rgb(32, 43, 255);")
		self.departure.setAlignment(Qt.AlignCenter)
		self.departure.setObjectName("departure")
		self.gridLayout.addWidget(self.departure, 2, 1, 1, 1)
		self.label_2 = QLabel(self)
		self.label_2.setStyleSheet("font: 25pt \"Agency FB\";")
		self.label_2.setAlignment(Qt.AlignCenter)
		self.label_2.setObjectName("label_2")
		self.gridLayout.addWidget(self.label_2, 2, 2, 1, 2)
		self.label_9 = QLabel(self)
		self.label_9.setStyleSheet("font: 10pt \"HY헤드라인M\";")
		self.label_9.setAlignment(Qt.AlignCenter)
		self.label_9.setObjectName("label_9")
		self.gridLayout.addWidget(self.label_9, 4, 2, 1, 4)
		self.time_1 = QLabel(self)
		self.time_1.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.time_1.setAlignment(Qt.AlignCenter)
		self.time_1.setObjectName("time_1")
		self.gridLayout.addWidget(self.time_1, 5, 2, 1, 4)
		self.time_2 = QLabel(self)
		self.time_2.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.time_2.setAlignment(Qt.AlignCenter)
		self.time_2.setObjectName("time_2")
		self.gridLayout.addWidget(self.time_2, 6, 2, 1, 4)
		self.time_3 = QLabel(self)
		self.time_3.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.time_3.setAlignment(Qt.AlignCenter)
		self.time_3.setObjectName("time_3")
		self.gridLayout.addWidget(self.time_3, 7, 2, 1, 4)
		self.time_4 = QLabel(self)
		self.time_4.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.time_4.setAlignment(Qt.AlignCenter)
		self.time_4.setObjectName("time_4")
		self.gridLayout.addWidget(self.time_4, 8, 2, 1, 4)
		self.time_5 = QLabel(self)
		self.time_5.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.time_5.setAlignment(Qt.AlignCenter)
		self.time_5.setObjectName("time_5")
		self.gridLayout.addWidget(self.time_5, 9, 2, 1, 4)
		self.label_8 = QLabel(self)
		self.label_8.setStyleSheet("font: 10pt \"HY헤드라인M\";")
		self.label_8.setAlignment(Qt.AlignCenter)
		self.label_8.setObjectName("label_8")
		self.gridLayout.addWidget(self.label_8, 4, 1, 1, 1)
		self.label_15 = QLabel(self)
		self.label_15.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.label_15.setAlignment(Qt.AlignCenter)
		self.label_15.setObjectName("label_15")
		self.gridLayout.addWidget(self.label_15, 5, 1, 1, 1)
		self.label_16 = QLabel(self)
		self.label_16.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.label_16.setAlignment(Qt.AlignCenter)
		self.label_16.setObjectName("label_16")
		self.gridLayout.addWidget(self.label_16, 6, 1, 1, 1)
		self.label_17 = QLabel(self)
		self.label_17.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.label_17.setAlignment(Qt.AlignCenter)
		self.label_17.setObjectName("label_17")
		self.gridLayout.addWidget(self.label_17, 7, 1, 1, 1)
		self.label_18 = QLabel(self)
		self.label_18.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.label_18.setAlignment(Qt.AlignCenter)
		self.label_18.setObjectName("label_18")
		self.gridLayout.addWidget(self.label_18, 8, 1, 1, 1)
		self.label_19 = QLabel(self)
		self.label_19.setStyleSheet("font: 8pt \"HY헤드라인M\";")
		self.label_19.setAlignment(Qt.AlignCenter)
		self.label_19.setObjectName("label_19")
		self.gridLayout.addWidget(self.label_19, 9, 1, 1, 1)
		self.label_20 = QLabel(self)
		self.label_20.setStyleSheet("color: rgb(12, 234, 64);")
		self.label_20.setAlignment(Qt.AlignCenter)
		self.label_20.setObjectName("label_20")
		self.gridLayout.addWidget(self.label_20, 5, 0, 1, 1)
		self.label_21 = QLabel(self)
		self.label_21.setStyleSheet("color: rgb(12, 234, 64);")
		self.label_21.setAlignment(Qt.AlignCenter)
		self.label_21.setObjectName("label_21")
		self.gridLayout.addWidget(self.label_21, 6, 0, 1, 1)
		self.label_22 = QLabel(self)
		self.label_22.setStyleSheet("color: rgb(12, 234, 64);")
		self.label_22.setAlignment(Qt.AlignCenter)
		self.label_22.setObjectName("label_22")
		self.gridLayout.addWidget(self.label_22, 7, 0, 1, 1)
		self.label_23 = QLabel(self)
		self.label_23.setStyleSheet("color: rgb(12, 234, 64);")
		self.label_23.setAlignment(Qt.AlignCenter)
		self.label_23.setObjectName("label_23")
		self.gridLayout.addWidget(self.label_23, 8, 0, 1, 1)
		self.label_24 = QLabel(self)
		self.label_24.setStyleSheet("color: rgb(12, 234, 64);")
		self.label_24.setAlignment(Qt.AlignCenter)
		self.label_24.setObjectName("label_24")
		self.gridLayout.addWidget(self.label_24, 9, 0, 1, 1)
		self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

		self.destination.setText("없음")
		self.label_4.setText("[ 셔틀버스 시간표 ]")
		self.departure.setText("없음")
		self.label_2.setText("→")
		self.label_9.setText("탑승 시간")
		self.time_1.setText("탑승 가능한 버스가 없습니다.")
		self.time_2.setText("탑승 가능한 버스가 없습니다.")
		self.time_3.setText("탑승 가능한 버스가 없습니다.")
		self.time_4.setText("탑승 가능한 버스가 없습니다.")
		self.time_5.setText("탑승 가능한 버스가 없습니다.")
		self.label_8.setText("순서")
		self.label_15.setText("[ 1 ]")
		self.label_16.setText("[ 2 ]")
		self.label_17.setText("[ 3 ]")
		self.label_18.setText("[ 4 ]")
		self.label_19.setText("[ 5 ]")
		self.label_20.setText("★")
		self.label_21.setText("★")
		self.label_22.setText("★")
		self.label_23.setText("★")
		self.label_24.setText("★")


	def render(self, bus_list):
		text_widget = [self.time_1, self.time_2, self.time_3, self.time_4, self.time_5]
		idx = 0
		if len(bus_list):
			self.destination.setText(bus_list[0][1])
			self.departure.setText(bus_list[0][0])
			for i in bus_list:
				text_widget[idx].setText('{} -> [ 출발까지 {}시간 {}분 ]'.format(i[2], i[3], i[4]))
				idx = idx + 1